### ISSUE TITLE
Prepare synthetic data

### ISSUE THREAD

**Issue by joaoherrera** [joaoherrera/blood-pressure-recognition#1]
Create synthetic data of digits to train a label recognition model. A valid sample is an image with a sequence of digits [0 - 9]. Digital display fonts are preferred (example [here](https://www.google.com/search?q=digital+display+font&sxsrf=ALiCzsbE_dRjb1kNt6UMdOSkjcPfOw2JfQ:1652019541291&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiEtK6vjND3AhWEFbkGHZO7AcUQ_AUoAXoECAEQAw&biw=1920&bih=936&dpr=1)).

**Tasks:**
- [x] Download open source fonts of digital displays.
- [x] Generate synthetic images and annotations.
- [x] Create a script to encode the dataset into the LDMB format.
- [x] Generate a LMDB dataset.
